Repository haskell-beam/beam, pull requests merged in 2020-08, with the labels that each got.

#500 Use Integral for SQL Int values in beam-core
  beam-core/Database/Beam/Query/Aggregate.hs
  beam-core/Database/Beam/Query/Combinators.hs
  beam-core/Database/Beam/Query/Extensions.hs
  beam-core/test/Database/Beam/Test/SQL.hs
Labels: breaking change

#497 Use explicitly sized integer types for Postgres-specific functions
  beam-postgres/Database/Beam/Postgres/PgCrypto.hs
  beam-postgres/Database/Beam/Postgres/PgSpecific.hs
Labels: breaking change

#436 Fix emitting of SQL 92 DECIMAL type
  beam-core/Database/Beam/Backend/SQL/Builder.hs
  beam-postgres/Database/Beam/Postgres/Syntax.hs
  beam-sqlite/Database/Beam/Sqlite/Syntax.hs
Labels: breaking change

#464 Add update', save' which use `SqlBool`s
  beam-core/Database/Beam/Query.hs
  beam-core/Database/Beam/Query/Combinators.hs
Labels: enhancement

#507 Fix the types of some Postgres operators that only work with jsonb
  beam-postgres/Database/Beam/Postgres/PgSpecific.hs
Labels: breaking change

#511 Fix SQLite IN with row values and add tests
  beam-core/Database/Beam/Query.hs
  beam-core/Database/Beam/Query/Ord.hs
  beam-postgres/test/Database/Beam/Postgres/Test/Select.hs
  beam-sqlite/Database/Beam/Sqlite/Connection.hs
  beam-sqlite/test/Database/Beam/Sqlite/Test.hs
  beam-sqlite/test/Database/Beam/Sqlite/Test/Select.hs
Labels: bug

#505 Remove instances for ambiguously sized integers
  beam-core/Database/Beam/Backend/Internal/Compat.hs
  beam-core/Database/Beam/Backend/SQL/AST.hs
  beam-core/Database/Beam/Backend/SQL/Builder.hs
  beam-core/Database/Beam/Backend/SQL/SQL92.hs
  beam-core/Database/Beam/Query/Combinators.hs
  beam-core/Database/Beam/Query/CustomSQL.hs
  beam-core/beam-core.cabal
  beam-core/test/Database/Beam/Test/SQL.hs
  beam-core/test/Database/Beam/Test/Schema.hs
  beam-migrate/Database/Beam/Haskell/Syntax.hs
  beam-migrate/Database/Beam/Migrate/Generics/Tables.hs
  beam-migrate/Database/Beam/Migrate/Log.hs
  beam-migrate/Database/Beam/Migrate/Simple.hs
  beam-postgres/Database/Beam/Postgres/Syntax.hs
  beam-postgres/Database/Beam/Postgres/Types.hs
  beam-postgres/examples/Pagila/Schema/CustomMigrateExample.hs
  beam-postgres/examples/Pagila/Schema/V0001.hs
  beam-postgres/examples/Pagila/Test.hs
  beam-postgres/test/Database/Beam/Postgres/Test/DataTypes.hs
  beam-postgres/test/Database/Beam/Postgres/Test/Marshal.hs
  beam-sqlite/Database/Beam/Sqlite/Connection.hs
  beam-sqlite/Database/Beam/Sqlite/Syntax.hs
Labels: breaking change
